site_url: https://ntn-boilerplate.netlify.app/
logo_url: https://ntn-boilerplate.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  label: 'Blog'
  folder: 'content/blog'
  create: true
  format: 'frontmatter'
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  # editor:
  #   preview: true
  fields:
    - { label: 'Title', name: 'title', widget: 'string', required: true }
    - {
        label: 'Description',
        name: 'description',
        widget: 'string',
        required: false,
      }
    - { label: 'Body', name: 'body', widget: 'markdown', required: false }
