export default {
  siteUrl: 'https://www.johnlaborde.com',
  siteName: '',
  author: 'John La Borde',
  email: 'mailto:info@johnlaborde.com',
  avatar: 'john.jpeg',
  avatarAlt: 'John La Borde display picture',
  twitterHandle: '@johnlaborde',
  twitter: '',
  github: 'https://github.com/cjlaborde',
  facebook: '',
  instagram: '',
  linkedIn: 'https://www.linkedin.com/in/christian-la-borde/',
  siteTitle: 'John La Borde blog',
  siteDesc: 'A site that specialize combining web development with marketing.',
  mainImage: '',
  siteType: 'website',
};
